title: Smilodon Software
description: Website for Smilodon Software client acquisition and blog
baseurl: ""
url: "https://smilodon.co"

theme: null

markdown: kramdown
highlighter: rouge

permalink: /:title

collections:
  posts:
    output: true
    permalink: /blog/:title

exclude:
  - SPEC.md
  - README.md
  - CHANGELOG.md
  - designs/
